version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: TOF-DB
      POSTGRES_USER: tof-user
      POSTGRES_PASSWORD: tof-user
    ports:
      - "5434:5432"
    expose:
      - 5434
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local